import { Pattern } from "../pattern/pattern";

import type { JDevice } from "shared/json";
import type { Partition } from "../partition";

//=================================================================
/**
 * {@link patternGenerator} takes the {@link JDevice}s generated by {@link Partition}s
 * and combine them into {@link Pattern}s.
 */
//=================================================================
export function* patternGenerator(partitions: readonly Partition[]): Generator<Pattern> {
	const buffer: JDevice[] = new Array(partitions.length);
	for(const devices of recursiveDeviceGenerator(partitions, 0, buffer)) {
		const pattern = new Pattern(devices);
		if(pattern.$valid) yield pattern;
	}
}


function* recursiveDeviceGenerator(
	partitions: readonly Partition[], depth: number, buffer: JDevice[]
): Generator<JDevice[]> {
	const partition = partitions[depth];
	for(const device of partition.$devices.$values()) {
		buffer[depth] = device;
		if(depth + 1 < partitions.length) {
			yield* recursiveDeviceGenerator(partitions, depth + 1, buffer);
		} else {
			yield buffer.concat();
		}
	}
}
