minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@mutsuntsai/*"
onlyBuiltDependencies:
  - "@swc/core"
  - "core-js"
  - es5-ext
  - "oxc-resolver"
  - sharp
  - "ttf2woff2"
  - "unrs-resolver"
overrides:
  js-yaml: ^4.1.1
  magic-string: ^0.30.0
peerDependencyRules:
  allowAny:
    - eslint
publicHoistPattern:
  - "@rspack/core"
  - "@popperjs/core"
  - "@pixi/*"
  - "@vue/*"
