minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@mutsuntsai/*"
allowBuilds:
  "@swc/core": true
  core-js: true
  es5-ext: true
  oxc-resolver: true
  sharp: true
  ttf2woff2: true
  unrs-resolver: true
overrides:
  js-yaml: ^4.1.1
  magic-string: ^0.30.0
peerDependencyRules:
  allowAny:
    - eslint
publicHoistPattern:
  - "@rspack/core"
  - "@popperjs/core"
  - "@pixi/*"
  - "@vue/*"
