# https://docs.astral.sh/ruff/settings/#format
[tool.ruff]
line-length = 130

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"

# https://docs.pytest.org/en/stable/reference/customize.html
[tool.pytest.ini_options]
testpaths = [
	"src/client/plugins/optimizer/python/tests"
]
