blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/bp-studio/box-pleating-studio/discussions
    about: Do you have questions or need any help? Use Discussions instead!
